# Ref: https://goreleaser.com/ci/actions/
name: goreleaser
on:
  push:
    # KJP versions will use normal semantic versioning with a suffix indicating the upstream Volcano release.
    # e.g. v0.0.1-volcano1.7.0
    # When Volcano is upgraded to 1.9:
    # v2.0.0-volcano1.9.0 <<< major external change
    tags:
      - 'v*.*.*-volcano*.*.*'
permissions:
  # needed to create releases
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
